---
title: "Dependent assignment"
output: github_document
---

```{r, include=F}
library(tidyverse)
library(reticulate)
```

```{r, include=F}
df <- iris %>% 
  select(length = Sepal.Length, width = Sepal.Width)
```

### R example

[Tidyverse](https://www.tidyverse.org/) allows us to use newly created/modified variables within a single `mutate` assignment. Note for the example below, `area` is dependent on the new `length` and `width` variables.

```{r}
# measure in mm instead of cm and compute area
df %>% 
  mutate(
    length = length * 10,
    width = width * 10,
    area = length * width) %>% 
  head(5)
```

### Python example

Dependent assignment in pandas (as of 0.25.x) requires a workaround using [anonymous functions](https://github.com/pandas-dev/pandas/issues/14207).

```{python, include=F}
import pandas as pd
df = pd.DataFrame(r.df)
```

```{python}
(df
  .assign(
    length = df["length"] * 10,
    width = df["width"] * 10,
  # area = df["length"] * df["width"] this will throw an error 
    area = lambda df: df["length"] * df["width"])
  .head(5))
```

Get the [print-friendly version](dependent_assign.pdf).
